# Generated by Django 4.2.2 on 2023-07-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_listening',
            name='user',
        ),
    ]
